import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    height: 55,
    paddingVertical: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  logoutButton: {
    marginRight: "auto",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#C6C6C6",
    padding: 8,
    borderRadius: 16,
  },
  container: {
    flex: 1,
    marginTop: 20,
    marginBottom: 30,
    position: "relative",
  },
  logoutLabel: { color: "white", fontSize: 14, fontWeight: 600 },
  fab: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#7F3DFF",
    width: 56,
    height: 56,
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  empty: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  emptyLabel: { color: "#292B2D", fontSize: 14, fontWeight: 500 },
  recentLabel: {
    color: "#292B2D",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 20,
  },
  transactions: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  transaction: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F6F6F6",
    borderRadius: 32,
    padding: 16,
  },
  left: { display: "flex", flexDirection: "row", gap: 10 },
  iconContainer: {
    width: 60,
    height: 60,
    padding: 10,
    borderRadius: 16,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  food: {
    backgroundColor: "#FDD5D7",
  },
  shopping: {
    backgroundColor: "#FCEED4",
  },
  subscription: {
    backgroundColor: "#EEE5FF",
  },
  icon: {
    width: 30,
    height: 30,
  },
  center: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  categoryLabel: { fontSize: 16, fontWeight: "600", color: "#292B2D" },
  descriptionLabel: { fontSize: 13, fontWeight: "600", color: "#91919F" },
  amountLabel: { fontSize: 16, fontWeight: "700", color: "#FD3C4A" },
});
